### PR TITLE
init go modules

### PR DESCRIPTION
**Pull request by rafaeleyng**
See #7

### CODE REVIEW

**Comment by stuart-mclaren** [comment]
Hi,

In order to pass checks the .travis.yml file will need to be updated.

The 'go' section will need to change from this

```
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip
```
to something like this:

```
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip
```

Please mention in the commit message that the minimum version is being bumped to 1.11 because gin now requires the http.SameSite attribute which is only supported in version 1.11 onwards.

Similarly, in the same .travis.yml file, the following section

```
install:
  - go get github.com/gin-gonic/gin
  - go get github.com/opentracing/opentracing-go
  - go get github.com/uber/jaeger-client-go
  - go get github.com/uber/jaeger-client-go/zipkin
```

Should be changed to use the equivalent `go mod` commands.
Then the travis-ci checks should pass.

Thanks!

**Comment by rafaeleyng** [comment]
Hi, @stuart-mclaren, thanks for the input. I'm asking myself if these changes are worth it. It seems that nobody is looking at this project, and this MR will never be looked at.

**Comment by stuart-mclaren** [comment]
Hey @rafaeleyng,

I will look at (and merge) your change if we can get it past Travis CI.

**Comment by rafaeleyng** [comment]
Hey @stuart-mclaren , I didn't realize you were a maintainer 😅 

I did the changes, could you check it now?

About the `install` part of the Travis, I just removed everything because `go test` should just download the dependencies.

**Review by stuart-mclaren — APPROVED** [review]
Thanks, looks good to me.

**Pull request merged**
